# extrae lon y lat de gfs bruto

In [10]:
lat = ds.latitude.values
lat

array([ 90.  ,  89.75,  89.5 ,  89.25,  89.  ,  88.75,  88.5 ,  88.25,
        88.  ,  87.75,  87.5 ,  87.25,  87.  ,  86.75,  86.5 ,  86.25,
        86.  ,  85.75,  85.5 ,  85.25,  85.  ,  84.75,  84.5 ,  84.25,
        84.  ,  83.75,  83.5 ,  83.25,  83.  ,  82.75,  82.5 ,  82.25,
        82.  ,  81.75,  81.5 ,  81.25,  81.  ,  80.75,  80.5 ,  80.25,
        80.  ,  79.75,  79.5 ,  79.25,  79.  ,  78.75,  78.5 ,  78.25,
        78.  ,  77.75,  77.5 ,  77.25,  77.  ,  76.75,  76.5 ,  76.25,
        76.  ,  75.75,  75.5 ,  75.25,  75.  ,  74.75,  74.5 ,  74.25,
        74.  ,  73.75,  73.5 ,  73.25,  73.  ,  72.75,  72.5 ,  72.25,
        72.  ,  71.75,  71.5 ,  71.25,  71.  ,  70.75,  70.5 ,  70.25,
        70.  ,  69.75,  69.5 ,  69.25,  69.  ,  68.75,  68.5 ,  68.25,
        68.  ,  67.75,  67.5 ,  67.25,  67.  ,  66.75,  66.5 ,  66.25,
        66.  ,  65.75,  65.5 ,  65.25,  65.  ,  64.75,  64.5 ,  64.25,
        64.  ,  63.75,  63.5 ,  63.25,  63.  ,  62.75,  62.5 ,  62.25,
      

In [2]:
import numpy as np
okok= '/home/fernando.huaranca/datosmunin/Gsmap_24hs/Gsmap_R0.25_24hs_2005-06-14.npz'
a = np.load(okok)


In [3]:
a.files

['pp_daily', 'longitudes', 'latitudes']

In [5]:
a['pp_daily'].shape

(297, 281)

In [6]:
a['latitudes']

array([ 15.  ,  14.75,  14.5 ,  14.25,  14.  ,  13.75,  13.5 ,  13.25,
        13.  ,  12.75,  12.5 ,  12.25,  12.  ,  11.75,  11.5 ,  11.25,
        11.  ,  10.75,  10.5 ,  10.25,  10.  ,   9.75,   9.5 ,   9.25,
         9.  ,   8.75,   8.5 ,   8.25,   8.  ,   7.75,   7.5 ,   7.25,
         7.  ,   6.75,   6.5 ,   6.25,   6.  ,   5.75,   5.5 ,   5.25,
         5.  ,   4.75,   4.5 ,   4.25,   4.  ,   3.75,   3.5 ,   3.25,
         3.  ,   2.75,   2.5 ,   2.25,   2.  ,   1.75,   1.5 ,   1.25,
         1.  ,   0.75,   0.5 ,   0.25,   0.  ,  -0.25,  -0.5 ,  -0.75,
        -1.  ,  -1.25,  -1.5 ,  -1.75,  -2.  ,  -2.25,  -2.5 ,  -2.75,
        -3.  ,  -3.25,  -3.5 ,  -3.75,  -4.  ,  -4.25,  -4.5 ,  -4.75,
        -5.  ,  -5.25,  -5.5 ,  -5.75,  -6.  ,  -6.25,  -6.5 ,  -6.75,
        -7.  ,  -7.25,  -7.5 ,  -7.75,  -8.  ,  -8.25,  -8.5 ,  -8.75,
        -9.  ,  -9.25,  -9.5 ,  -9.75, -10.  , -10.25, -10.5 , -10.75,
       -11.  , -11.25, -11.5 , -11.75, -12.  , -12.25, -12.5 , -12.75,
      

In [20]:
a.files

['lon', 'lat', 'arr_0']

In [11]:
#Cargamos librerias
import numpy
import os 
import xarray as xr

#Ruta de algun archivo .grib2 de GFS
path_archivo = '/home/fernando.huaranca/datos/DATOS_REFORECAST/apcp_sfc/apcp_sfc_2000010200_c00.grib2'

ds = xr.open_dataset(path_archivo)

lat = ds.latitude.values
lon = ds.longitude.values

#Latitudes y longitudes (box)
lat_north = 15
lat_south = -59
lon_east = 330
lon_west = 260

#Recorta la seccion de sudamerica o la que se desee
#LATITUDES

lat_index = np.where((lat <=lat_north) & (lat >= lat_south))[0]


lat = lat[lat_index]

#LONGITUDES
lon_index = np.where((lon >= lon_west) & (lon <= lon_east))[0]

lon = lon[lon_index]

#np.savez('grid.npz',latitudes_gfs =lat,longitudes_gfs=lon)

In [15]:
lat.min

<function ndarray.min>

In [4]:
import numpy as np
okok = '/home/fernando.huaranca/datosmunin2/Thesis_Neuronal_Network/work/Datos_Brutos/gsmap/grid.npz'
ok = np.load(okok)

In [8]:
ok['latitudes_gfs']

array([ 15.  ,  14.75,  14.5 ,  14.25,  14.  ,  13.75,  13.5 ,  13.25,
        13.  ,  12.75,  12.5 ,  12.25,  12.  ,  11.75,  11.5 ,  11.25,
        11.  ,  10.75,  10.5 ,  10.25,  10.  ,   9.75,   9.5 ,   9.25,
         9.  ,   8.75,   8.5 ,   8.25,   8.  ,   7.75,   7.5 ,   7.25,
         7.  ,   6.75,   6.5 ,   6.25,   6.  ,   5.75,   5.5 ,   5.25,
         5.  ,   4.75,   4.5 ,   4.25,   4.  ,   3.75,   3.5 ,   3.25,
         3.  ,   2.75,   2.5 ,   2.25,   2.  ,   1.75,   1.5 ,   1.25,
         1.  ,   0.75,   0.5 ,   0.25,   0.  ,  -0.25,  -0.5 ,  -0.75,
        -1.  ,  -1.25,  -1.5 ,  -1.75,  -2.  ,  -2.25,  -2.5 ,  -2.75,
        -3.  ,  -3.25,  -3.5 ,  -3.75,  -4.  ,  -4.25,  -4.5 ,  -4.75,
        -5.  ,  -5.25,  -5.5 ,  -5.75,  -6.  ,  -6.25,  -6.5 ,  -6.75,
        -7.  ,  -7.25,  -7.5 ,  -7.75,  -8.  ,  -8.25,  -8.5 ,  -8.75,
        -9.  ,  -9.25,  -9.5 ,  -9.75, -10.  , -10.25, -10.5 , -10.75,
       -11.  , -11.25, -11.5 , -11.75, -12.  , -12.25, -12.5 , -12.75,
      

In [1]:
import glob
import numpy as np  


In [2]:
data_path ='/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8'
file_list = glob.glob(data_path+'/gsmap_gauge.*.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz')
file_list

['/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20000914.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20180528.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20191007.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20100108.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20070520.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20010629.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20100529.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20080411.0.1d.daily.00Z-23Z.v8.0000.0.dat.gz',
 '/home/fernando.huaranca/datos/Datos_GSMAP/daily_G_v8/gsmap_gauge.20100531.0.1d.daily.0

In [6]:
file_list[0].split('.')[2]

'20000914'

In [9]:
import xesmf as xe


In [32]:
#Extraccion de array de latitudes y longitudes de un archivo gsmap
import numpy as np
import os
#La carpeta donde se almacenan los archivos de gsmap
folder_gfs = '/home/fernando.huaranca/datosmunin3/GFS_24hs'

#Un archivo random
file_gfs = 'GFS_R0.25_24hs_2000-01-04.npz'

#Path
path_gfs = os.path.join(folder_gfs,file_gfs)

#Abro archivo

npz_gfs = np.load(path_gfs)

#Extraigo mis variables de interes
#Al extraerlo se debe hacer una correcion en los datos esto debido a que 


latitudes_gfs = npz_gfs['latitudes']
longitudes_gfs = npz_gfs['longitudes']


In [35]:
np.savez('/home/fernando.huaranca/datosmunin2/archivos/grid.npz',latitudes_gfs=latitudes_gfs,longitudes_gfs=longitudes_gfs)

In [10]:

#La carpeta donde se almacenan los archivos de gsmap
folder_gsmap = '/home/fernando.huaranca/datosmunin3/Gsmap_24hs'

#Un archivo random
file_gsmap = 'Gsmap_R0.1_24hs_2000-01-04.npz'

#Path
path_gsmap = os.path.join(folder_gsmap,file_gsmap)

#Abro archivo

npz_gsmap = np.load(path_gsmap)

#Extraigo mis variables de interes
#Al extraerlo se debe hacer una correcion en los datos esto debido a que 


latitudes_gsmap = npz_gsmap['latitudes']
longitudes_gsmap = npz_gsmap['longitudes']

In [22]:
'/home/fernando.huaranca/datosmunin3/Gsmap_24hs/Gsmap_R0.1_24hs_2000-01-04.npz'

(750,)

In [23]:
longitudes_gfs.max()

329.75

In [24]:
longitudes_gsmap.max()

329.9500000000001

In [11]:
grid_in = {'lon':longitudes_gsmap,'lat':latitudes_gsmap}
grid_out = {'lon':longitudes_gfs,'lat':latitudes_gfs}

In [29]:
regridder = xe.Regridder(grid_in,grid_out,'conservative')
regridder

AttributeError: 'dict' object has no attribute 'cf'

In [16]:
lat_out

array([ 14.75,  14.5 ,  14.25,  14.  ,  13.75,  13.5 ,  13.25,  13.  ,
        12.75,  12.5 ,  12.25,  12.  ,  11.75,  11.5 ,  11.25,  11.  ,
        10.75,  10.5 ,  10.25,  10.  ,   9.75,   9.5 ,   9.25,   9.  ,
         8.75,   8.5 ,   8.25,   8.  ,   7.75,   7.5 ,   7.25,   7.  ,
         6.75,   6.5 ,   6.25,   6.  ,   5.75,   5.5 ,   5.25,   5.  ,
         4.75,   4.5 ,   4.25,   4.  ,   3.75,   3.5 ,   3.25,   3.  ,
         2.75,   2.5 ,   2.25,   2.  ,   1.75,   1.5 ,   1.25,   1.  ,
         0.75,   0.5 ,   0.25,   0.  ,  -0.25,  -0.5 ,  -0.75,  -1.  ,
        -1.25,  -1.5 ,  -1.75,  -2.  ,  -2.25,  -2.5 ,  -2.75,  -3.  ,
        -3.25,  -3.5 ,  -3.75,  -4.  ,  -4.25,  -4.5 ,  -4.75,  -5.  ,
        -5.25,  -5.5 ,  -5.75,  -6.  ,  -6.25,  -6.5 ,  -6.75,  -7.  ,
        -7.25,  -7.5 ,  -7.75,  -8.  ,  -8.25,  -8.5 ,  -8.75,  -9.  ,
        -9.25,  -9.5 ,  -9.75, -10.  , -10.25, -10.5 , -10.75, -11.  ,
       -11.25, -11.5 , -11.75, -12.  , -12.25, -12.5 , -12.75, -13.  ,
      

In [15]:
lat_in

array([-5.995e+01, -5.985e+01, -5.975e+01, -5.965e+01, -5.955e+01,
       -5.945e+01, -5.935e+01, -5.925e+01, -5.915e+01, -5.905e+01,
       -5.895e+01, -5.885e+01, -5.875e+01, -5.865e+01, -5.855e+01,
       -5.845e+01, -5.835e+01, -5.825e+01, -5.815e+01, -5.805e+01,
       -5.795e+01, -5.785e+01, -5.775e+01, -5.765e+01, -5.755e+01,
       -5.745e+01, -5.735e+01, -5.725e+01, -5.715e+01, -5.705e+01,
       -5.695e+01, -5.685e+01, -5.675e+01, -5.665e+01, -5.655e+01,
       -5.645e+01, -5.635e+01, -5.625e+01, -5.615e+01, -5.605e+01,
       -5.595e+01, -5.585e+01, -5.575e+01, -5.565e+01, -5.555e+01,
       -5.545e+01, -5.535e+01, -5.525e+01, -5.515e+01, -5.505e+01,
       -5.495e+01, -5.485e+01, -5.475e+01, -5.465e+01, -5.455e+01,
       -5.445e+01, -5.435e+01, -5.425e+01, -5.415e+01, -5.405e+01,
       -5.395e+01, -5.385e+01, -5.375e+01, -5.365e+01, -5.355e+01,
       -5.345e+01, -5.335e+01, -5.325e+01, -5.315e+01, -5.305e+01,
       -5.295e+01, -5.285e+01, -5.275e+01, -5.265e+01, -5.255e

In [11]:
import numpy as np
import xarray as xr
import xesmf as xe

# Carga tus datos desde el archivo NPZ
data_npz = np.load('/home/fernando.huaranca/datosmunin3/Gsmap_24hs/Gsmap_R0.1_24hs_2000-01-04.npz')

# Extrae las variables de longitud y latitud
lon_in = data_npz['longitudes']
lat_in = data_npz['latitudes']
data_in = data_npz['pp_daily']  # Ajusta el nombre según tus datos

# Crea un conjunto de datos xarray
ds_in = xr.Dataset({'data_in': (['lat', 'lon'], data_in)},
                   coords={'lon': lon_in, 'lat': lat_in})

# Carga el conjunto de datos de salida desde otro archivo NPZ
data_out_npz = np.load('/home/fernando.huaranca/datosmunin3/GFS_24hs/GFS_R0.25_24hs_2000-01-04.npz')
lon_out = data_out_npz['longitudes']
lat_out = data_out_npz['latitudes']

# Crea un conjunto de datos xarray para el conjunto de datos de salida
ds_out = xr.Dataset(coords={'lon': lon_out, 'lat': lat_out})

# Crea el Regridder
regridder = xe.Regridder(ds_in, ds_out, 'conservative')

# Realiza la regridificación
resultado = regridder(ds_in)
resultado

<xarray.Dataset>
Dimensions:  (lat: 319, lon: 279)
Coordinates:
  * lon      (lon) float64 260.2 260.5 260.8 261.0 ... 329.0 329.2 329.5 329.8
  * lat      (lat) float64 14.75 14.5 14.25 14.0 ... -64.0 -64.25 -64.5 -64.75
Data variables:
    data_in  (lat, lon) float32 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Attributes:
    regrid_method:  conservative

In [12]:
data_in

array([[0.072     , 0.072     , 0.12      , ..., 0.33600003, 0.33600003,
        3.384     ],
       [0.96      , 0.74399996, 0.984     , ..., 0.264     , 0.264     ,
        3.192     ],
       [0.91199994, 1.152     , 1.2       , ..., 0.288     , 0.264     ,
        0.264     ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [5]:
resultado.

<xarray.DataArray 'lon' (lon: 279)>
array([260.25, 260.5 , 260.75, ..., 329.25, 329.5 , 329.75])
Coordinates:
  * lon      (lon) float64 260.2 260.5 260.8 261.0 ... 329.0 329.2 329.5 329.8

In [30]:
latitudes_gfs


array([ 14.75,  14.5 ,  14.25,  14.  ,  13.75,  13.5 ,  13.25,  13.  ,
        12.75,  12.5 ,  12.25,  12.  ,  11.75,  11.5 ,  11.25,  11.  ,
        10.75,  10.5 ,  10.25,  10.  ,   9.75,   9.5 ,   9.25,   9.  ,
         8.75,   8.5 ,   8.25,   8.  ,   7.75,   7.5 ,   7.25,   7.  ,
         6.75,   6.5 ,   6.25,   6.  ,   5.75,   5.5 ,   5.25,   5.  ,
         4.75,   4.5 ,   4.25,   4.  ,   3.75,   3.5 ,   3.25,   3.  ,
         2.75,   2.5 ,   2.25,   2.  ,   1.75,   1.5 ,   1.25,   1.  ,
         0.75,   0.5 ,   0.25,   0.  ,  -0.25,  -0.5 ,  -0.75,  -1.  ,
        -1.25,  -1.5 ,  -1.75,  -2.  ,  -2.25,  -2.5 ,  -2.75,  -3.  ,
        -3.25,  -3.5 ,  -3.75,  -4.  ,  -4.25,  -4.5 ,  -4.75,  -5.  ,
        -5.25,  -5.5 ,  -5.75,  -6.  ,  -6.25,  -6.5 ,  -6.75,  -7.  ,
        -7.25,  -7.5 ,  -7.75,  -8.  ,  -8.25,  -8.5 ,  -8.75,  -9.  ,
        -9.25,  -9.5 ,  -9.75, -10.  , -10.25, -10.5 , -10.75, -11.  ,
       -11.25, -11.5 , -11.75, -12.  , -12.25, -12.5 , -12.75, -13.  ,
      

In [ ]:
import numpy as np
import xesmf as xe

# Cargar datos de la cuadrícula de entrada desde el archivo NPZ
data_in = np.load('ruta_a_tu_archivo_de_entrada.npz')
lon_in = data_in['lon']
lat_in = data_in['lat']
data_in_values = data_in['data_in']

# Cargar datos de la cuadrícula de salida desde otro archivo NPZ
data_out = np.load('ruta_a_tu_archivo_de_salida.npz')
lon_out = data_out['lon']
lat_out = data_out['lat']

# Crear el Regridder
regridder = xe.Regridder({'lon': lon_in, 'lat': lat_in}, {'lon': lon_out, 'lat': lat_out}, 'conservative')

# Realizar la regridificación
data_out_values = regridder(data_in_values)


In [8]:
import numpy as np
import xesmf as xe

# Carga tus datos desde el archivo NPZ
data_npz = np.load('/home/fernando.huaranca/datosmunin3/Gsmap_24hs/Gsmap_R0.1_24hs_2000-01-04.npz')

# Extrae las variables de longitud y latitud
lon_in = data_npz['longitudes']
lat_in = data_npz['latitudes']
data_in = data_npz['pp_daily']  # Ajusta el nombre según tus datos

# Carga el conjunto de datos de salida desde otro archivo NPZ
data_out_npz = np.load('/home/fernando.huaranca/datosmunin3/GFS_24hs/GFS_R0.25_24hs_2000-01-04.npz')
lon_out = data_out_npz['longitudes']
lat_out = data_out_npz['latitudes']

# Crear el Regridder
regridder = xe.Regridder({'lon': lon_in, 'lat': lat_in}, {'lon': lon_out, 'lat': lat_out}, 'conservative')

# Realizar la regridificación
resultado2 = regridder(data_in)
resultado2

AttributeError: 'dict' object has no attribute 'cf'

In [9]:
import numpy as np
import xesmf as xe

# Carga tus datos desde el archivo NPZ
data_npz = np.load('/home/fernando.huaranca/datosmunin3/Gsmap_24hs/Gsmap_R0.1_24hs_2000-01-04.npz')

# Extrae las variables de longitud y latitud
lon_in = data_npz['longitudes']
lat_in = data_npz['latitudes']
data_in = data_npz['pp_daily']  # Ajusta el nombre según tus datos

# Carga el conjunto de datos de salida desde otro archivo NPZ
data_out_npz = np.load('/home/fernando.huaranca/datosmunin3/GFS_24hs/GFS_R0.25_24hs_2000-01-04.npz')
lon_out = data_out_npz['longitudes']
lat_out = data_out_npz['latitudes']

# Crear el Regridder
regridder = xe.Regridder({'lon': lon_in, 'lat': lat_in}, {'lon': lon_out, 'lat': lat_out}, 'conservative')

# Realizar la regridificación
resultado = regridder(data_in)


AttributeError: 'dict' object has no attribute 'cf'

In [10]:
import numpy as np
import xesmf as xe

# Cargar tus datos desde el archivo NPZ
data_npz = np.load('/home/fernando.huaranca/datosmunin3/Gsmap_24hs/Gsmap_R0.1_24hs_2000-01-04.npz')

# Extraer las variables de longitud y latitud
lon_in = data_npz['longitudes']
lat_in = data_npz['latitudes']
data_in = data_npz['pp_daily']  # Ajustar el nombre según tus datos

# Cargar el conjunto de datos de salida desde otro archivo NPZ
data_out_npz = np.load('/home/fernando.huaranca/datosmunin3/GFS_24hs/GFS_R0.25_24hs_2000-01-04.npz')
lon_out = data_out_npz['longitudes']
lat_out = data_out_npz['latitudes']

# Crear las cuadrículas de entrada y salida con xesmf
grid_in = xe.grid({'lon': lon_in, 'lat': lat_in})
grid_out = xe.grid({'lon': lon_out, 'lat': lat_out})

# Crear el Regridder
regridder = xe.Regridder(grid_in, grid_out, 'conservative')

# Realizar la regridificación
resultado = regridder(data_in)


AttributeError: module 'xesmf' has no attribute 'grid'