In [5]:
from sklearn.metrics import confusion_matrix
import numpy as np

In [11]:
#Primera prueba
mod = np.array([[5,3,2],[6,1,8],[9,0,0]])
obs = np.array([[12,3,1],[16,9,1],[1,15,1]])

mod = mod.ravel() >= 5
obs = obs.ravel() >=5
#confusion_matrix(y_true=obs,y_pred=mod,labels=[True,False])

In [13]:
mod

array([ True, False, False,  True, False,  True,  True, False, False])

In [15]:
cm = confusion_matrix(y_true=obs,y_pred=mod,labels=[True,False])

In [16]:
cm.ravel()

array([2, 2, 2, 3])

In [40]:
#Otro
mod = np.array([[5,6,11],[1,7,9],[12,1,5]])
obs = np.array([[3,10,3],[5,7,11],[5,1,8]])
print(mod)
mod = mod.ravel() >=5
obs = obs.ravel() >=5

cm = confusion_matrix(y_true=obs,y_pred=mod,labels=[True,False])
cm

[[ 5  6 11]
 [ 1  7  9]
 [12  1  5]]


array([[5, 1],
       [2, 1]])

In [31]:
cm.ravel()

array([5, 1, 2, 1])